export interface Tag {
  id: string;
  name: string;
  food: TagsOnFoods[];
}

export interface TagsOnFoods {
  tagId: string;
  foodId: string;
  food: Food;
  tag: Tag;
}

export interface FoodsList {
  food: Food;
  foodId: string;
  roomId: string;
}

export interface Food {
  altName: string;
  country: string;
  createdAt: string;
  id: string;
  img: string;
  name: string;
  updatedAt: string; // Generated by https://quicktype.io
}

export type BookMarkFood = {
  altName: string;
  country: string;
  createdAt: string;
  id: string;
  img: string;
  name: string;
  tags: Tag[];
  updatedAt: string;
};

export type BookMarkTag = {
  foodId: string;
  tagId: string;
};
